### ISSUE TITLE
Please specify support in 1.20

### ISSUE THREAD

**Issue by ColonelGerdauf** [semper-idem/nonvflickering#4]
Currently, the mod in the platforms have the support numbers incorrectly configured.

- in Modrinth, the mod is cited support solely for `1.20`. This makes it difficult to download/update to 1.20.1 and beyond.
- in Curseforge, the same problem is happening, except launchers fail to recognize the availability to download, let alone update. It is cited as `no valid version found!` in Prism, for example.

What would help is to extend the written support from just 1.20 to 1.20-1.20.1

**Comment by semper-idem** [comment]
Sorry, Afaik I cannot specify mod is 1.20.* on mod pages, I have to add those labels manually and I'm not that involved with Minecraft atm to keep up with it's updates.

Anyway, updated on both pages, shouldn't cause problems anymore

I hope you meant just mod-pages site cause latest version of this mod is configured to run on 1.20.* and I've tested it to work
